version: '3.8'

services:
  postgresql:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: knowledge_window
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/knowledge_window
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./backend/migrations:/liquibase/changelog
    networks:
      - backend
    restart: on-failure

  knowledge-window-java:
    container_name: knowledge-window-java
    depends_on:
      - liquibase-migrations
    ports:
      - "8090:8090"
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8090
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/knowledge_window
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - files:/var/lib/files
    restart: on-failure
    
  knowledge-window-python:
    container_name: knowledge-window-python
    depends_on:
      - knowledge-window-java
    build:
      context: ./model
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: on-failure
    volumes:
      - files:/var/lib/files
    networks:
      - backend

  ollama:
    image: ollama/ollama:latest
    depends_on:
      - knowledge-window-python
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

    entrypoint: ollama run llama3.2:3b
    networks:
      - backend

volumes:
  postgresql: { }
  files: { }
  ollama: { }

networks:
  backend: {}